\documentclass[a4paper,11pt]{article}
\usepackage[margin=1in]{geometry}

\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}

\usepackage{graphicx}%
\usepackage{multirow}%
\usepackage{amsmath,amssymb,amsfonts}%
\usepackage{amsthm}%
\usepackage{mathrsfs}%
\usepackage[title]{appendix}%
\usepackage{xcolor}%

\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}

\usepackage{textcomp}%
\usepackage{manyfoot}%
\usepackage{booktabs}%
\usepackage{algorithm}%
\usepackage{algorithmicx}%
\usepackage{algpseudocode}%
\usepackage{listings}%
\usepackage{framed}% 
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
%%%%


\usepackage{tipa}
\usepackage{fge}
\usepackage{tipx}
\usepackage{multicol}
\usepackage{soul}
\usepackage{tikz}
\usepackage{tikz-qtree}
\usepackage{fge}
 \usepackage{qtree}
\usepackage[utf8]{inputenc}
\usepackage{mathptmx}
\usepackage{leipzig}

\usepackage{hyperref}
\usepackage{gb4e}
\makeglossaries
%%%%

\usepackage{gb4e}
\usepackage{cite}
%\usepackage[sectionbib]{natbib}

\newcommand{\secref}[1]{\S\ref{#1}}


\raggedbottom



\title{Variation of {[}v{]} in Cook Islands Māori}
\author{Quartz Colvin}
\date{}


\begin{document}
\maketitle

\section{Introduction}\label{introduction}

In this paper, we will do a statistical analysis of {[}v{]} across a sample of islands in Cook Islands Māori (CIM). It is known that in many dialects and other varieties of Māori, this phoneme can be realized as {[}w{]} or {[}v{]}. This paper aims to take a statistical approach to this generalization.

This paper has four sub-questions to investigate. First, how does the duration of w\textasciitilde v vary by island and second, how does intensity for w\textasciitilde v vary by island. The other two questions are about identifying information about the surface forms of w\textasciitilde v by island. Specifically, we will model f0 and f2 to determine whether certain islands realize a devoiced phoneme. Finally, an f2 model will help us determine which islands have higher rates of {[}w{]}s surfacing and which have more {[}v{]}s surfacing.

\subsection{Background (CIM)}\label{background-cim}

Cook Islands Māori is an Eastern Polynesian language indigenous to the Cook Islands. CIM is classified as \emph{Endangered} and has little intergenerational transmission. It is very closely related to Aotearoa Māori (New Zealand Māori), but is definitely different enough to be classified as a separate, but related language.

It is known across both Aotearoa Māori and CIM speakers that some speakers regularly pronounce their {[}v{]}s as {[}w{]}s, but it is not clear to anyone who does this more and what conditions it. In hopes of answering this question, I will compare various aspects of w\textasciitilde v phonemes across a sample of the Cook Islands. The islands in this study are Atiu, Mauke, Penrhyn, and Rarotonga.

\begin{figure}[!htbp]

{\centering \includegraphics[width=0.4\linewidth]{./figs/cook-islands-map} 

}
\caption{Map of Cook Islands.}\label{fig:unnamed-chunk-1}
\end{figure}

In the map above, you can see that Penrhyn is far in the northern group while the other three islands in our sample are part of the southern group. Lastly, it's relevant to note that Rarotongan CIM is considered to be the standard dialect of CIM and it hosts the capital of the Cook Islands.

\section{Methods}\label{methods}

The data for this project comes from a \href{https://catalog.paradisec.org.au/collections/SN1}{\textbf{large digital corpus}} managed by \href{https://www.paradisec.org.au/}{\textbf{PARADISEC}} (Nicholas 2012). Much of the data in this corpus was collected for Nicholas's dissertation work and while there is a \emph{lot} of data, it is largely unorganized.

In order to make large corpora like this as useful for linguistic research or revitalization projects as possible, the data needs to be fully annotated and organized. Given the sheer amount of data, it would take humans too long to annotate it all, and thus a team of linguists and Cook Islanders have started working together to develop NLP tools to accelerate this documentation (Coto-Solano et al.~2018).

As part of this broader collaborative NLP project, they have trained an improved forced alignment tool for CIM. So far, forced-aligned data has been used to investigate the glottal stop phoneme (Coto-Solano et al.~2018), but this segmented data can be used to do all kinds of phonetic analysis. The data in this paper comes from the PARADESEC corpus and was aligned by phoneme, and then corrected. The final Praat TextGrids are also available in the corpus. All acoustic measurements for these phonemes were extracted from Praat.

To reiterate, all of the data collection and processing to a usable format for this project was not done by me. Full credit for all of those previous steps goes to the linguists who worked on data collection and processing the data (Coto-Solano et al.~2018).

\section{Data}\label{data}

The following large data set has many columns. Here I show a preview of the data set and then discuss which columns will be relevant to the analysis later in the paper.

\begin{figure}[!htbp]

{\centering \includegraphics[width=0.7\linewidth]{./figs/raw\_data} 

}

\caption{ }\label{fig:Raw data}
\end{figure}

First, note that there is no `id' column but there is a column for the speaker's initials. I will use speaker in place of `id' because that is what was in this original data set. The `island' column states what island that speaker is from. This data only contains data from the four islands Atiu, Mauke, Penrhyn and Rarotonga. Duration corresponds to the total duration of the phoneme, and intensity is measured at the midpoint of the phoneme.

F0 values were taken at 20\%, 50\% and 80\% of each phoneme's total duration. Later, we will opt to use only the F0 values at 50\%, but that will be discussed more later. Finally, F2\_midpoint is f2 measured in Hz at the midpoint of that phoneme. All of the other columns are either straight-forward information or will be irrelevant for this paper.

\section{Analysis}\label{analysis}

This section readdresses the main questions about the w\textasciitilde v alternation. First, how does duration differ by island and second, how does intensity vary by island? Finally, do any islands have regular occurrence of {[}w{]} instead of {[}v{]} surfacing. For this final question, we will compare f0 and f2 separately.

Note that in all of my models, I did not control for where w\textasciitilde v occurs in the word, since I am looking at general frequency information and not doing a phonological analysis of specific environments in which {[}w{]} or {[}v{]} occurs more. Another important thing to note is that for each island, there were different numbers of speakers contributing to the data set. All of the Atiu data came from one speaker and it was the same for Penrhyn. The Mauke data came from four speakers and the Rarotonga data came from five speakers. Since there are different numbers of speakers from each of these islands, the models I will use to investigate each question will be linear mixed models.

\subsection{Duration by island}\label{duration-by-island}

The first step of comparing duration of w\textasciitilde v across these four islands is to make a smaller, tidy data set that only contains the relevant information. Below, I filter the data so that it only contains rows with the ``v'' phoneme. Then I arrange it by island and then by word, and I select only the columns ``speaker'', ``island'', ``word'' and duration. Finally, I save this filtered data set as a new csv file. After we have done this tidying process, the duration data set looks like this.


\begin{table}[!htbp]
\centering
\caption{Duration tidy data.}
\begin{tabular}{l|l|l|r}
\hline
speaker & island & word & duration\\
\hline
TA & Atiu & ava & 0.08\\
\hline
TA & Atiu & ava & 0.07\\
\hline
TA & Atiu & ava & 0.14\\
\hline
TA & Atiu & ava & 0.11\\
\hline
TA & Atiu & ava & 0.05\\
\hline
TA & Atiu & ava & 0.13\\
\hline
\end{tabular}
\end{table}

For a visual comparison, we will look at boxplots comparing duration across these four islands. 

\begin{figure}

{\centering \includegraphics[width=0.5\linewidth]{D2\_CIM\_files/figure-latex/print-duration-plot-1} 

}

\caption{Duration boxplot}\label{fig:print-duration-plot}
\end{figure}

The boxplot shows that average (mean) durations were pretty similar across these three islands. But for some reason, Penrhyn had a much larger range of durations than the other islands.

Now that we have an idea of what the general differences and similarities are for duration, we can fit the linear mixed effect model. In the code chunk. you can see that I account for the fact that number of speakers varies across the islands in the data set, and also that there are many instances of each word. These instances of each `word' are repeated by each speaker multiple times and by several speakers multiple times.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod\_dur }\OtherTok{\textless{}{-}} \FunctionTok{lmer}\NormalTok{(duration }\SpecialCharTok{\textasciitilde{}}\NormalTok{ island }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{speaker) }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{word), }\AttributeTok{data =}\NormalTok{ tidy\_dur)}
\end{Highlighting}
\end{Shaded}

\subsection{Intensity by island}\label{intensity-by-island}

Next is the intensity comparison across the four islands. Starting from the raw data set, we must filter it again so that it only has instances of the ``v'' phoneme and we filter everything except the ``speaker'', ``island'', ``word'', and ``intensity'' columns. Once the new data set has been made, it looks roughly like the following table, but extended of course.

\begin{table}[!htbp]
\centering
\caption{Duration tidy data.}
\begin{tabular}{l|l|l|r}
\hline
speaker & island & word & intensity\\
\hline
TA & Atiu & ava & 54.08202\\
\hline
TA & Atiu & ava & 58.06061\\
\hline
TA & Atiu & ava & 48.40481\\
\hline
TA & Atiu & ava & 54.18315\\
\hline
TA & Atiu & ava & 49.59224\\
\hline
TA & Atiu & ava & 53.07335\\
\hline
\end{tabular}
\end{table}

In the same way we did for the duration question, we will first look at a boxplot to visually see any clear differences in intensity across the Cook Islands. The code chunk to make the plot is below, and then the actual plot is printed below it.

\begin{figure}

{\centering \includegraphics[width=0.5\linewidth]{D2\_CIM\_files/figure-latex/print-intensity-plot-1} 

}

\caption{Intensity boxplot}\label{fig:print-intensity-plot}
\end{figure}

Initially, it is clear that Penrhyn has the lowest mean intensity for w\textasciitilde v. Mauke and Rarotonga have nearly the same mean intensity, and Atiu's mean is slighly lower, but not as low as Penrhyn's mean. Now that we know the general patterns, we can fit our linear mixed effects model. Dur to the same reasons as before, I model speaker and word as mixed effects in the intensity by island model. The code chunk below shows how I fit the model in R.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod\_intense }\OtherTok{\textless{}{-}} \FunctionTok{lmer}\NormalTok{(intensity }\SpecialCharTok{\textasciitilde{}}\NormalTok{ island }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{speaker) }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{word), }\AttributeTok{data =}\NormalTok{ tidy\_intense)}
\end{Highlighting}
\end{Shaded}

\subsection{Voicing by island}\label{voicing-by-island}

Moving on to the formant questions, first we will investigate how voicing of w\textasciitilde v differs across these four islands. In acoustic measurements, an F0 lower than 80 Hz is considered voiceless.

This time, we tidy the raw data set in a similar way but with one additional step. Since we have f0 values at three different intervals of the same morpheme, if we were to put all of those formant values in a new column and the percentage in another new column, then it would fabricate 3 times as many tokens that were not elicited from the speakers.

In order to limit this autocorrelation issue, I chose to only keep f0 values at the 50\% interval of the phoneme. I chose the 50\% interval because the middle of the duration seemed like the smartest choice to represent the average f0 value across the phoneme's duration. The code chunk below shows how I tidied this mini-data-set to answer the voicing question.

Once we have made this new, tidy data set, it looks like this. Again, if I showed the full table, it would have more than this one word and this one island. This is just the top few rows of the sorted table.

\begin{table}[!htbp]
\centering
\caption{F0 tidy data}
\begin{tabular}{l|l|l|r|r}
\hline
speaker & island & word & f0 & duration\\
\hline
TA & Atiu & ava & 127.0908 & 0.08\\
\hline
TA & Atiu & ava & 157.4397 & 0.07\\
\hline
TA & Atiu & ava & 134.1155 & 0.14\\
\hline
TA & Atiu & ava & 141.8125 & 0.11\\
\hline
TA & Atiu & ava & 118.2318 & 0.05\\
\hline
TA & Atiu & ava & 142.7506 & 0.13\\
\hline
\end{tabular}
\end{table}

This time, to compare f0 across the islands visually, we can plot this data onto a scatterplot. As you can see, I created an individual facet for each island and each color represents data from a particular speaker.

\begin{figure}

{\centering \includegraphics[width=0.75\linewidth]{D2\_CIM\_files/figure-latex/print-f0-plot-1} 

}

\caption{F0 by island}\label{fig:print-f0-plot}
\end{figure}

It's clear that the most drastic slope is in the Penrhyn plot, and the data for the islands with more speakers are much more spread out across the plot. To formally compare these different variables, we can again use a linear mixed effects model to see how f0 varies across these four Cook Islands. The model fitting is shown in the code chunk below.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod\_f0 }\OtherTok{\textless{}{-}} \FunctionTok{lmer}\NormalTok{(f0 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ island }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{speaker) }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{word), }\AttributeTok{data =}\NormalTok{ tidy\_f0)}
\end{Highlighting}
\end{Shaded}


\subsection{w \textasciitilde v distribution by island}\label{wv-distribution-by-island}

Finally we turn to the main research question: is there a correlation between island and how many {[}w{]} tokens surface? The acoustic measurement indicating a {[}w{]} is \textbf{less than 850 Hz.} For this question, we tidy the raw data set once again so that it only has data for ``v'', speaker, island, word, and f2 values. Once the data has been tidied, it generally looks like this.


\begin{table}[!htbp]
\centering
\caption{F2 tidy data.}
\begin{tabular}{l|l|l|r}
\hline
speaker & island & word & f2\\
\hline
TA & Atiu & ava & 964.3925\\
\hline
TA & Atiu & ava & 950.2333\\
\hline
TA & Atiu & ava & 2575.9621\\
\hline
TA & Atiu & ava & 961.5736\\
\hline
TA & Atiu & ava & 984.4541\\
\hline
TA & Atiu & ava & 896.0441\\
\hline
\end{tabular}
\end{table}

To visually compare the f2 values across these islands, we generate another boxplot.

\begin{figure}

{\centering \includegraphics[width=0.5\linewidth]{D2\_CIM\_files/figure-latex/print-f2-plot-1} 

}

\caption{F2 boxplot}\label{fig:print-f2-plot}
\end{figure}

From looking at the f2 boxplot, it's clear that Atiu has the lowest mean f2. The other three islands had more similar means, but Mauke and Penrhyn had some instances of w\textasciitilde v that had extremely high F2 measurements. Regardless, the boxes for each island look different, so we know what to expect when we fit a linear mixed effects model. The code chunk for fitting this model is below.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod\_f2 }\OtherTok{\textless{}{-}} \FunctionTok{lmer}\NormalTok{(f2 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ island }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{speaker) }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{|}\NormalTok{word), }\AttributeTok{data =}\NormalTok{ tidy\_f2)}
\end{Highlighting}
\end{Shaded}






\section{Results}\label{results}

This section interprets the statistical results for each individual model, and interprets a nested model comparison for each of the four models from the previous section. 




\subsection{Duration}

Data were analyzed using a linear mixed effects model (as implemented by the lme4 (version 1.1-37) package in R 4.5.0 (2025-04-11 ucrt)). This model included \textit{duration} as the dependent variable, and \textit{island, speaker} and \textit{word} as fixed factors. 


The fixed effects for this individual model are in Table \ref{dur-fixed}. The \textbf{standard error (SE)} for each island were very small, around 0.01, indicating that the mean of the sample is an accurate reflection of the actual populations mean.  The \textbf{t-values} for each island except Atiu were all lower than 2, indicating that they are not statistically significant between the islands, unless a speaker is from Atiu. The \textbf{degrees of freedom (df)} for Mauke and Penrhyn were a little under 6 and the df for Rarotonga was a bit above 6. For each island, the \textbf{betas} are very close to 0, which indicates there is not a linear relationship between duration and island. 


\begin{table}[!htbp]
\centering
\small
\begin{tabular}{l|r|r|r|r}
\hline
  & betas & SE & t-val & df \\
\hline
Atiu & 0.064761 & 0.013130 & 4.932 & 6.339137 \\
Mauke & -0.001702 & 0.014390 & -0.118 & 5.858906 \\
Penrhyn & 0.019477 & 0.018068 & 1.078 & 5.690570 \\
Rarotonga & -0.018439 & 0.014557 & -1.267 & 6.292463 
\end{tabular}
\caption{Duration fixed effects}
\label{dur-fixed}
\end{table}



As for the random effects for the duration model, these are shown in Table \ref{dur-random}. The \textbf{standard deviations} for both word and speaker were very small, indicating that the data for these two variables were very clustered around the mean. \textbf{Variance} was also extremely small.

\begin{table}[!htbp]
\centering
\small
\begin{tabular}{l|r|r|r}
\hline
 group & name & Std. Dev. & Variance  \\
\hline
word & (intercept) & 0.02707 & 0.0007328 \\
speaker & (intercept) & 0.01231 & 0.0001517 \\
Residual &  & 0.03192 & 0.0010189 
\end{tabular}
\caption{Duration random effects}
\label{dur-random}
\end{table}


\noindent{\textbf{Model fit and assumptions.}}

\textcolor{red}{fill in???}\\


\noindent{\textbf{Nested model comparison.}}

The model summary for the nested model comparison is in Table \ref{dur-nested}. For this, I utilized the `anova()' function in R and ommited the columns I don't interpret. Significance of main effects and all possible interactions were assessed using hierarchical partitioning of the variance via nested model comparisons. Experiment-wise, alpha was set at 0.05. The model summary table for the nested model comparison for duration is shown in the following table. 

\begin{table}[!htbp]
\centering
\begin{tabular}{l|r|r|r|r|r}
\hline
   & AIC & BIC & logLik  & Chisq & Pr($>$Chisq)\\
\hline
dur\_null & -3287.577 & -3277.981 & 1645.789  & NA & NA\\
\hline
dur\_island & -3367.804 & -3343.815 & 1688.902  & 86.22701  & 0\\
\hline
dur\_add  & -3397.532 & -3368.745 & 1704.766  & 31.72802  & 0\\
\hline
mod\_dur & -3433.078 & -3399.493 & 1723.539  & 37.54595  & 0\\
\hline
\end{tabular}
\caption{Model summary for duration.}
\label{dur-nested}
\end{table}

The \textbf{Akaike Information Criterion} (AIC) and \textbf{Bayesian Information Criterion} (BIC) were extremely large negative numbers for  each nested model, indicating that we have a well-fit model. The \textbf{log-likelihood} (logLik) values were also very large, further indicating that the model is well-fit to the data. The values for \textbf{Chisq} were high; the values for the additive model and the whole duration model were in the 30s, but the Chisq value for the dur\_island model was much larger at 86.22701. These values quantify the difference in fit between the models being compared. The greatest difference was for the island parameter.

Lastly, the \textbf{Pr($\>$Chisq)} values for each model (excluding the null model) were 0. As this is less than 0.05, this suggests that the most complex model was a better fit than the nested models, which means the extra effects taken into account in the larger model were necessary. 


%\textcolor{red}{residual plots (qq-plot, residual vs. fitted, residual vs order)???}






\subsection{Intensity}


Data were analyzed using a linear mixed effects model (as implemented by the lme4 (version 1.1-37) package in R 4.5.0 (2025-04-11 ucrt)). This model included \textit{intensity} as the dependent variable, and \textit{island, speaker} and \textit{word} as fixed factors. 

The model summary fixed effects for the individual intensity model is shown in Table \ref{intensity-fixed}. The \textbf{standard error (SE)} for each island were {large, around 11-15, indicating that the mean of the sample is not an accurate reflection of the actual populations mean.  The \textbf{t-values} for each island were all lower than 2, indicating that they are not statistically significant between the islands. 


\begin{table}[!htbp]
\centering
\small
\begin{tabular}{l|r|r|r|r}
\hline
  & betas & SE & t-val  & df \\
\hline
Atiu & 57.919 & 10.864 & 5.331  & 6.184 \\
Mauke & 2.534 & 12.137 & 0.209  & 6.165 \\
Penrhyn & -7.853 & 15.347 & -0.512 & 6.156 \\
Rarotonga & 2.095 & 11.947 & 0.175 & 6.261
\end{tabular}
\caption{Intensity fixed effects}
\label{intensity-fixed}
\end{table}

The \textbf{degrees of freedom (df)} for all islands were around 6. For Mauke, \textbf{beta} was 2.534, which indicates that being a speaker from Mauke, intensity is expected to be higher. For Penrhyn, beta was -7.853, which indicates that being a speaker from Penrhyn, intensity is expected to be much lower. For Rarotonga, beta was 2.095, which indicates a speaker from Rarotonga is expected to have higher intensity, similar to Mauke. Atiu had the largest positive value for beta at 58, indicating the highest linear relationship between being a speaker from Atiu and having higher intensity.

As for the random effects, which are reported in Table \ref{intensity-random}, \textbf{standard deviation} for word and speaker were higher for the intensity model. For word, standard deviation was 4.377, so the data for intensity by word were less clustered around the mean. The standard deviation was even higher for speaker, at 10.834, so the speaker data was even more spread out. \textbf{Variance} values were consistent with this, as the variance for word was high at 19.16, and the variance for speaker was much larger at 117.38. 

\begin{table}[!htbp]
\centering
\small
\begin{tabular}{l|r|r|r}
\hline
 group & name & Std. Dev. & Variance  \\
\hline
word & (intercept) & 4.377 & 19.16 \\
speaker & (intercept) & 10.834 & 117.38 \\
Residual &  & 5.851 & 34.24 
\end{tabular}
\caption{Intensity random effects}
\label{intensity-random}
\end{table}






\noindent{\textbf{Model fit and assumptions.}}

\textcolor{red}{fill in???}\\


\noindent{\textbf{Nested model comparison.}}

The model summary for the nested model comparison is in Table \ref{intensity-nested}. For this, I utilized the `anova()' function in R and ommited the columns I don't interpret.

The intensity data were analyzed using a linear mixed effects model. Intensity was the criterion with \textit{island, speaker} and \textit{word} as predictors. Main effects and the interactions between \textit{island, speaker} and \textit{word} were assessed using nested model comparisons. Experiment-wise, alpha was set at 0.05.

\begin{table}[!htbp]
\centering
\small
\begin{tabular}{l|r|r|r|r|r}
\hline
   & AIC & BIC & logLik  & Chisq  & Pr($>$Chisq)\\
\hline
intensity\_null &  6613.473 & 6623.065 & -3304.737  & NA  & NA\\
\hline
intensity\_island &  6500.268 & 6524.246 & -3245.134  & 119.20555  & 0\\
\hline
intensity\_add &  5977.433 & 6006.207 & -2982.717  & 524.83480 & 0\\
\hline
mod\_intense & 5902.351 & 5935.921 & -2944.176  & 77.08165  & 0\\
\hline
\end{tabular}
\caption{Model summary for intensity.}
\label{intensity-nested}
\end{table}


The \textbf{AIC} and \textbf{BIC} were extremely large numbers for  each nested model, indicating that we do \textit{not} have a well-fit model. The \textbf{log-likelihood} (logLik) values were very small, further indicating that the model is not well-fit to the data. The values for \textbf{Chisq} were extremely high; the values for the island model were 119.20555, the value for the additive model was 524.83480, and the value for the whole intensity model was 77.08165. These values quantify the difference in fit between the models being compared. The greatest difference was for the additive model, which included \textit{intensity, island} and \textit{speaker} parameters, excluding the \textit{word} parameter. 

Lastly, the \textbf{Pr($\>$Chisq)} values for each model (excluding the null model) were 0. As this is less than 0.05, this suggests that the most complex model was a better fit than the nested models, which means the extra effects taken into account in the larger model were necessary. 


%\textcolor{red}{residual plots (qq-plot, residual vs. fitted, residual vs order)???}



\subsection{F0}

Data were analyzed using a linear mixed effects model (as implemented by the lme4 (version 1.1-37) package in R 4.5.0 (2025-04-11 ucrt)). This model included \textit{intensity} as the dependent variable, and \textit{island, speaker} and \textit{word} as fixed factors. 

The fixed effects for the individual F0 model are reported in Table \ref{f0-fixed}. The \textbf{standard error (SE)} for each island were very large, at least 24, indicating that the mean of the sample is not an accurate reflection of the actual populations mean.  The \textbf{t-values} for each island were all lower than 2, indicating that they are not statistically significant between the islands. The \textbf{degrees of freedom (df)} for all islands were around 3.4. 

For each island, the \textbf{betas} are very spread out. For Mauke, beta was about 24, Penrhyn's beta was -3, and Rarotonga's beta was nearly 50. This indicates that a speaker from Mauke or Rarotonga is expected to have an increased f0 value (the increase is greater for Rarotonga). But, for Penrhyn, the f0 is expected to be lower for a speaker from Penrhyn. Again, Atiu has the highest positive number for beta, at 141, indicating a strong linear relationship between being from Atiu and having a higher f0 value.

\begin{table}[!htbp]
\centering
\small
\begin{tabular}{l|r|r|r|r}
\hline
  & betas & SE & t-val & df \\
\hline
Atiu & 140.935 & 24.584 & 5.733 & 3.466 \\
Mauke & 24.229 & 27.450 & 0.883 & 3.448 \\
Penrhyn & -3.145 & 34.660 & -0.091 & 3.423 \\
Rarotonga & 49.950 & 27.269 & 1.832 & 3.564
\end{tabular}
\caption{F0 fixed effects}
\label{f0-fixed}
\end{table}



As for the random effects, reported in Table \ref{f0-random}, the \textbf{standard deviations} for word and speaker were somewhat large, with standard deviation for word being 11.41 and standard deviation for speaker being 24.34. This indicates that the data for both was spread out, but more so for speaker. \textbf{Variance} for both word and speaker were also large, with variance for word being 130.1, and variance for speaker being 592.5. So, variability in this model was quite high.

\begin{table}[!htbp]
\centering
\small
\begin{tabular}{l|r|r|r}
\hline
 group & name & Std. Dev. & Variance  \\
\hline
word & (intercept) & 11.41 & 130.1 \\
speaker & (intercept) & 24.34 & 592.5 \\
Residual &  & 28.67 & 822.2 
\end{tabular}
\caption{F0 random effects}
\label{f0-random}
\end{table}









\noindent{\textbf{Model fit and assumptions.}}

Since we have f0 values at three different intervals of the same morpheme, if we were to put all of those formant values in a new column and the percentage in another new column, then it would fabricate 3 times as many tokens that were not elicited from the speakers.

In order to limit this \textit{autocorrelation} issue, I chose to only keep f0 values at the 50\% interval of the phoneme. I chose the 50\% interval because the middle of the duration seemed like the smartest choice to represent the average f0 value across the phoneme's duration.\\

\noindent{\textbf{Nested model comparison.}}

The model summary for the nested model comparison is in Table \ref{f0-nested}. For this, I utilized the `anova()' function in R and ommited the columns I don't interpret.

The f0 data were analyzed using a linear mixed effects model. F0 (Hz) was the criterion with \textit{island, speaker} and \textit{word} as predictors. Main effects and the interactions between \textit{island, speaker} and \textit{word} were assessed using nested model comparisons. Experiment-wise, alpha was set at 0.05.


\begin{table}[!htbp]
\centering
\begin{tabular}{l|r|r|r|r|r}
\hline
  & AIC & BIC & logLik  & Chisq  & Pr($>$Chisq)\\
\hline
f0\_null & 8419.866 & 8429.335 & -4207.933 & NA  & NA\\
\hline
f0\_island & 8243.201 & 8266.874 & -4116.601  & 182.66463  & 0.00e+00\\
\hline
f0\_add &  8153.415 & 8181.822 & -4070.707  & 91.78646  & 0.00e+00\\
\hline
mod\_f0 & 8139.651 & 8172.793 & -4062.826 & 15.76368  & 7.18e-05\\
\hline
\end{tabular}
\caption{Model summary for f0}
\label{f0-nested}
\end{table}

The \textbf{AIC} and \textbf{BIC} were extremely large numbers for  each nested model, indicating that we do \textit{not} have a well-fit model. The \textbf{log-likelihood} (logLik) values were very small (negative) numbers, further indicating that the model is not well-fit to the data. 

The values for \textbf{Chisq} were somewhat high; the values for the island model were 182.66, the value for the additive model was 91.79, and the value for the whole intensity model was 15.76. These values quantify the difference in fit between the models being compared. The greatest difference was for the island model, which included \textit{f0} and \textit{island} parameters, excluding the \textit{speaker} and \textit{word} parameters. 

Lastly, the \textbf{Pr($\>$Chisq)} values for each model (excluding the null model) were extremely small. As they are all less than 0.05, this suggests that the most complex model was a better fit than the nested models, which means the extra effects taken into account in the larger model were necessary. 


%\textcolor{red}{residual plots (qq-plot, residual vs. fitted, residual vs order)???}










\subsection{F2}

Data were analyzed using a linear mixed effects model (as implemented by the lme4 (version 1.1-37) package in R 4.5.0 (2025-04-11 ucrt)). This model included \textit{f2} (Hz) as the dependent variable, and \textit{island, speaker} and \textit{word} as fixed factors. 

The fixed effects for the individual f2 model are reported in Table \ref{f2-fixed}. The \textbf{standard error (SE)} for each island were very large, at least 83, indicating that the mean of the sample is not an accurate reflection of the actual populations mean.  The \textbf{t-values} for each island were all higher than 2, indicating that they \textit{are} statistically significant between the islands. 

\begin{table}[!htbp]
\centering
\small
\begin{tabular}{l|r|r|r|r}
\hline
  & betas & SE & t-val & df \\
\hline
Atiu & 1142.411 & 83.412 & 13.696 & 5.643 \\
Mauke & 297.881 & 90.354 & 3.297 & 4.946 \\
Penrhyn & 384.930 & 111.231 & 3.461 & 4.466 \\
Rarotonga & 389.099 & 94.770 & 4.106 & 6.027
\end{tabular}
\caption{F2 fixed effects}
\label{f2-fixed}
\end{table}


The \textbf{degrees of freedom (df)} for Mauke and Penrhyn were under 5 and the df for Rarotonga was a bit above 6. For each island, the \textbf{betas} are very large. For Atiu, beta was 1142.41, Mauke's beta was 297, Penrhyn was 384, and Rarotonga was 389. This indicates all islands are associated with a large increase in F2, with the highest being Atiu. 


As for random effects, reported in Table \ref{f2-random}, \textbf{standard deviations} for word and speaker were quite high again. For word, the standard deviation was high at 193.80, and for speaker it was at 68.01. This indicates that for both word and speaker, the data was quite spread out, but the data for word was much more spread out around the mean. 


\begin{table}[!htbp]
\centering
\small
\begin{tabular}{l|r|r|r}
\hline
 group & name & Std. Dev. & Variance  \\
\hline
word & (intercept) & 193.80 & 37558 \\
speaker & (intercept) & 68.01 & 4625 \\
Residual &  & 394.20 & 155390 
\end{tabular}
\caption{F2 random effects}
\label{f2-random}
\end{table}

\textbf{Variability} was also very large for word and speaker in the F2 model, with variance for word being 37558 and variance for speaker being 4625. \\









\noindent{\textbf{Model fit and assumptions.}}

\textcolor{red}{fill in???}\\


\noindent{\textbf{Nested model comparison.}}

The model summary for the nested model comparison is in Table \ref{f2-nested}. For this, I utilized the `anova()' function in R and ommited the columns I don't interpret.

The f2 data were analyzed using a linear mixed effects model. F2 was the criterion with \textit{island, speaker} and \textit{word} as predictors. Main effects and the interactions between \textit{island, speaker} and \textit{word} were assessed using nested model comparisons. Experiment-wise, alpha was set at 0.05.

The \textbf{AIC} and \textbf{BIC} were extremely large numbers for  each nested model, indicating that we do \textit{not} have a well-fit model. The \textbf{log-likelihood} (logLik) values were very small (negative) numbers, further indicating that the model is not well-fit to the data. 

\begin{table}[!htbp]
\centering
\begin{tabular}{l|r|r|r|r|r}
\hline
   & AIC & BIC & logLik  & Chisq &  Pr($>$Chisq)\\
\hline
f2\_null  & 13451.07 & 13460.66 & -6723.536  & NA  & NA\\
\hline
f2\_island & 13394.48 & 13418.46 & -6692.240  & 62.592574  & 0.0000000\\
\hline
f2\_add  & 13394.49 & 13423.27 & -6691.246  & 1.987579 & 0.1585942\\
\hline
mod\_f2  & 13330.46 & 13364.03 & -6658.229 & 66.034384 &  0.0000000\\
\hline
\end{tabular}
\caption{Model summary for f2.}
\label{f2-nested}
\end{table}

The values for \textbf{Chisq} were somewhat high, except for the additive model. The Chisq value for f2\_island was high at 62.59, and the value for the full mod\_f2 was 66.03. The additive model's Chisq value was low at 1.99. These values quantify the difference in fit between the models being compared. The greatest difference was for the island model and the full model. The island model included \textit{f2, island} parameters and the full model included \textit{f2, island, speaker,} and \textit{word}. Since the additive model was so low, the \textit{speaker} parameter didn't indicate a huge difference in the model fit. 

Lastly, the \textbf{Pr($\>$Chisq)} values for each model (excluding the null model) were extremely small, but the additive model was slightly larger at 0.16. Since the additive model was greater than 0.05, this indicates that the less complex models were a better fit than the more complex ones in the nested model comparison. 


%\textcolor{red}{residual plots (qq-plot, residual vs. fitted, residual vs order)???}


\subsection{Interim summary}


\textcolor{red}{fill in ???}








\subsection{Formant models}

Recall that we had the following p-values in each model for each island.

\begin{table}[!htbp]
\caption{\label{tab:p-vals-table}P-values from each model.}
\centering
\begin{tabular}[t]{c|c|c|c|c}
\hline
Island & Duration & Intensity & F0 & F2\\
\hline
Atiu & 0.00225 & 0.00161 & 0.00702 & 0.0000152\\
\hline
Mauke & 0.90982 & 0.84133 & 0.43464 & 0.0219000\\
\hline
Penrhyn & 0.32459 & 0.62670 & 0.93276 & 0.0216200\\
\hline
Rarotonga & 0.25014 & 0.86632 & 0.14965 & 0.0062600\\
\hline
\end{tabular}
\end{table}

In the duration model, only Atiu did \emph{not} have a statistically significant (\textgreater{} 0.05) p-value (0.00225), but the other three islands had statistically significant p-values. Penrhyn and Rarotonga had very similar p-values but Mauke had a significantly higher p-value. In the intensity model, again, all of the islands had statistically significant p-values (\textgreater{} 0.05) except Atiu. The highest p-values amongst the other three islands was for Make and Rarotonga. The model for F0 revealed that each island except for Atiu had a significant p-value. Penrhyn had the highest p-value in the F0 column.

Recall that an F0 value lower than \textbf{100 Hz} indicates that the phoneme is voiceless. We can tidy the F0 dataset once again to add a new column stating whether the w\textasciitilde v in that row surfaces as voiced or voiceless. The counts of voiced and voiceless tokens for each island are summarized in the following table.

\begin{table}[!htbp]
\centering
\caption{Voiced and voiceless phoneme counts.}
\begin{tabular}{l|l|l|l|l|l|l|l}
\hline
island & Atiu & Mauke & Mauke & Penrhyn & Penrhyn & Rarotonga & Rarotonga\\
\hline
voiced & voiced & voiced & voiceless & voiced & voiceless & voiced & voiceless\\
\hline
freq & 114 & 404 & 14 & 167 & 1 & 139 & 2\\
\hline
\end{tabular}
\end{table}

With the count information, we can manually calculate the percentages of voiceless w\textasciitilde v tokens surfacing in each group (island) of the data set. So, to answer the voicing question, only Atiu had zero voiceless tokens surfacing. Mauke had a voiceless surface form 3.10\% of the time, which was the highest percentage of voiceless surface forms in the data set. Penrhyn and Rarotonga had similar rates of voiceless surface forms, with voiceless phonemes surfacing 0.59\% of the time for Penrhyn, and 1.28\% of the time for Rarotonga.

Finally, the F2 model revealed no statistically significant differences in F2 values between these four islands, as all of the p-values in the F2 column are less than 0.05.

The final research question for us to address is the w\textasciitilde v question. An F2 value \textbf{less than 850 Hz} is taken to indicate a {[}w{]} phoneme on the surface instead of a {[}v{]}. To answer this question in percentages, we can create an additional column that states whether F2 is greater or less than 850 Hz. If F2 is less than 850, the value in the new column is ``w'', and if it is greater than 850, the value in the new column is ``v''.

Once we have the counts of ``w'' and ``v'' surface forms for each island, we can calculate the percentages. The table with the frequency column is shown below.

\begin{table}[!htbp]
\centering
\caption{Frequency counts.}
\begin{tabular}{l|l|l|l|l|l|l|l|l}
\hline
island & Atiu & Atiu & Mauke & Mauke & Penrhyn & Penrhyn & Rarotonga & Rarotonga\\
\hline
surface\_form & v & w & v & w & v & w & v & w\\
\hline
freq & 97 & 21 & 424 & 26 & 163 & 7 & 151 & 5\\
\hline
\end{tabular}
\end{table}

I manually calculated the percentages of {[}w{]}s surfacing in each group (island) based on the frequencies in the table above. The percent of {[}w{]}s in Atiu was 17.80\%, 5.75\% for Mauke, 4.12\% for Penrhyn and 3.21\% for Rarotonga.

\section{Conclusion}\label{conclusion}

Through doing this statistical analysis of w\textasciitilde v tokens across Atiu, Mauke, Penrhyn, and Rarotonga, we found that duration, intensity, and F0 by island are statistically significant for all islands except Atiu. Duration was the most significant for Mauke, and intensity and F0 were the most significant for Penrhyn.

The F2 model revealed no statistical significance between the F2 values and which island a speaker was from. However, to answer the voiced or voiceless question, we calculated percentages that show that all islands except Atiu had voiceless surface forms for w\textasciitilde v, with Mauke having the highest percentage of 3.10\%.

In order to answer the final question, which islands have more {[}w{]} surface forms, we also calculated percentages. These percentages showed that all of these four islands had {[}w{]} phonemes realized, but the highest percentage of {[}w{]}s surfacing was in Atiu, where {[}v{]} was realized as {[}w{]} 17.80\% of the time.


\begin{thebibliography}{20}
\addtolength{\leftmargin}{0.2in} % sets up alignment with the following line.
\setlength{\itemindent}{-0.2in}

\bibitem{CotoSolano} Coto-Solano, Nicholas \& Wray. 2018. Development of Natural Language Processing Tools for Cook Islands Māori. In \emph{Proceedings of Australasian Language Technology Association Workshop}, pages 26-33.

\bibitem{Nicholas} Nicholas, Sally Akevai (collector), 2012. Te Vairanga Tuatua o te Te Reo Māori o te Pae Tonga: Cook Islands Māori (Southern dialects) . Collection SN1 at catalog.paradisec.org.au {[}Open Access{]}. \url{https://dx.doi.org/10.4225/72/56E9793466307}

\bibitem{Thieberger} Thieberger \& Barwick. 2012. Keeping records of language diversity in melanesia, the pacific and regional archive for digital sources in endangered cultures (paradisec). \emph{Melanesian languages on the edge of Asia: Challenges for the 21st Century,} pages 239-53.

\end{thebibliography}

\clearpage
\renewcommand{\listfigurename}{Figure captions}

\clearpage
\renewcommand{\listtablename}{Table captions}


\end{document}
